post http://localhost:5000/create_answer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IjVmZWNlYjY2IiwidXNlcmlkIjotMSwiaWF0IjoxNjc2ODA4NjIzfQ.YHPIvwzSGf6TkBRDi3ZM4NLTz7rY6GVjCSkmlfCJIUs
Content-Type: application/json

{
   "postid": 4,
   "body" : "harsha vardhan"
}